- platform: haveibeenpwned
  email: 
    - !secret pwned_one
    - !secret pwned_two
    - !secret pwned_three
    - !secret pwned_four
    - !secret pwned_five
    - !secret pwned_six
    - !secret pwned_seven
    - !secret pwned_eight
