- platform: metoffice
  api_key: !secret metoffice_key
  monitored_conditions:
    - weather
    - temperature
    - feels_like_temperature
    - wind_speed
    - wind_direction
    - wind_gust
    - visibility
    - visibility_distance
    - uv
    - precipitation
    - humidity
