- platform: template
  sensors:
    office_motion:
      friendly_name: 'Office motion'
      value_template: '{% if is_state("sensor.office_multi_burglar", "0") %} false {% else %} true {% endif %}'
