- platform: template
  sensors:
    garage_door_l:
      friendly_name: 'Garage door (tilt), bike'
      device_class: 'opening'
      value_template: '{% if is_state("sensor.garage_door_bike_alarm_level", "255") %} open {% else %} closed {% endif %}'
