- platform: template
  sensors:
    garage_door_r:
      friendly_name: 'Garage door (tilt), car'
      device_class: 'opening'
      value_template: '{% if is_state("sensor.garage_car_alarm_level", "255") %} open {% else %} closed {% endif %}'
