alias: 'All away lights off'
initial_state: 'on'
trigger:
  platform: state
  entity_id: group.my_adults
  from: 'home'
  to: 'not_home'
condition:
  condition: state
  entity_id: media_player.samsung_tv_remote
  state: 'on'
action:
  service: scene.turn_on
  entity_id: scene.all_lights_off
