alias: 'Bedhead light dim'
initial_state: 'on'
trigger:
  platform: time
  at: '22:15:00'
condition:
  condition: state
  entity_id: light.master_bedroom_bedhead
  state: 'on'
action:
  service: light.turn_on
  data:
    entity_id: light.master_bedroom_bedhead
    brightness: 120
    color_temp: 450
    transition: 30
