alias: 'Bedhead light left on'
initial_state: 'on'
trigger:
  platform: state
  entity_id: light.master_bedroom_bedhead
  to: 'on'
  for: 
    minutes: 30
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
    - condition: state
      entity_id: media_player.person2
      state: 'off'
action:
  - service: light.turn_off
    data:
      entity_id: light.master_bedroom_bedhead
      transition: 30
