alias: 'Bedhead light dim'
initial_state: 'on'
trigger:
  platform: time
  at: '22:15:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.master_bedroom_bedhead
      state: 'on'
    - condition: template
      value_template: '{{ states.light.master_bedroom_bedhead.attributes.brightness|default(0) > 120 }}'
action:
  service: light.turn_on
  data:
    entity_id: light.master_bedroom_bedhead
    brightness: 120
    color_temp: 450
    transition: 30
