initial_state: 'on'
alias: 'Number on in the morning'
trigger:
  platform: time
  at: '06:00:00'
condition: 
  condition: sun
  before: sunrise
action:
  service: switch.turn_on
  entity_id: switch.number_sign_switch
