initial_state: 'on'
alias: 'Number on at sunset'
trigger:
  platform: numeric_state
  entity_id: sun.sun
  value_template: "{{ state.attributes.elevation }}"
  below: 3
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.number_sign_switch
      state: 'off'
    - condition: time
      after: '12:00:00'
action:
  service: switch.turn_on
  entity_id: switch.number_sign_switch
