alias: 'person1 up'
initial_state: 'on'
trigger:
  platform: state
  entity_id: media_player.person1
  to: 'playing'
condition:
  condition: time
  before: '07:00:00'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
