initial_state: 'on'
alias: 'Test ZWave network'
trigger:
  - platform: time
    at: '06:00:00'
  - platform: time
    at: '15:00:00'
  - platform: time
    at: '23:00:00'
action:
  service: zwave.test_network
