alias: 'Utility door open before sunrise turn on'
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.utility_door
  to: 'open'
condition:
  condition: and
  conditions:
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: switch.garden_lights_switch
      state: 'off'
action:
  - service: script.turn_on
    entity_id: script.garden_door_before_sunrise
